version: "3.3"
services:
    database:
        container_name: "InfluxDB"
        environment:
            - INFLUXDB_DB=Storj
        image: influxdb
        ports:
            - 8086:8086
    collector:
        build: .
        container_name: "Storj-Collector"
        environment:
            - DBServer=database
            - DBPort=8086
            - DBName=Storj
            - NodeName=
            - NodeURL=
            - RefreshInterval=60
            - Remote=false
            - SSHServer=
            - SSHUsername=
            - SSHPassword=
            - SSHLog=
        restart: always
        volumes:
            - ./ressources:/app
            # If Remote is set to false
            # mount log file to /app/[NodeName].log